### ISSUE TITLE
Recommend not using "template" in tag title.

### ISSUE THREAD

**Issue by semisight** [vaven-platform/gtm-vaven-tag-template#1]
https://github.com/vaven-platform/gtm-vaven-tag-template/blob/56be4dca7ada15a6fcc9df4fc89db9305b197aa1/template.tpl#L16

I recommend using "Vaven Tag" as the tag title, as this best describes what this template does.

That said, this is a recommendation, not a requirement. Let me know if you'd like to move forward with the current name.

**Comment by vaven-platform** [comment]
Tag title changed to "Vaven Tag".
